# Generated by Django 5.1 on 2024-11-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelist',
            name='image_links',
            field=models.JSONField(default=list),
        ),
    ]
